import type { Metadata } from "next";

import { Vazirmatn } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/provider/theme-provider";
const vazir = Vazirmatn({
  variable: "--font-vazir-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <ThemeProvider>
        <body className={`${vazir.variable}  `}>
          <main className="container">{children}</main>
        </body>
      </ThemeProvider>
    </html>
  );
}
